/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecondRouteImport } from './routes/second'
import { Route as FilesCategoryRouteImport } from './routes/files-category'
import { Route as ExploreFilesRouteImport } from './routes/explore-files'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const SecondRoute = SecondRouteImport.update({
  id: '/second',
  path: '/second',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesCategoryRoute = FilesCategoryRouteImport.update({
  id: '/files-category',
  path: '/files-category',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreFilesRoute = ExploreFilesRouteImport.update({
  id: '/explore-files',
  path: '/explore-files',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/explore-files': typeof ExploreFilesRoute
  '/files-category': typeof FilesCategoryRoute
  '/second': typeof SecondRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/explore-files': typeof ExploreFilesRoute
  '/files-category': typeof FilesCategoryRoute
  '/second': typeof SecondRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/explore-files': typeof ExploreFilesRoute
  '/files-category': typeof FilesCategoryRoute
  '/second': typeof SecondRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/explore-files'
    | '/files-category'
    | '/second'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/explore-files' | '/files-category' | '/second'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/explore-files'
    | '/files-category'
    | '/second'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ExploreFilesRoute: typeof ExploreFilesRoute
  FilesCategoryRoute: typeof FilesCategoryRoute
  SecondRoute: typeof SecondRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/second': {
      id: '/second'
      path: '/second'
      fullPath: '/second'
      preLoaderRoute: typeof SecondRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files-category': {
      id: '/files-category'
      path: '/files-category'
      fullPath: '/files-category'
      preLoaderRoute: typeof FilesCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore-files': {
      id: '/explore-files'
      path: '/explore-files'
      fullPath: '/explore-files'
      preLoaderRoute: typeof ExploreFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ExploreFilesRoute: ExploreFilesRoute,
  FilesCategoryRoute: FilesCategoryRoute,
  SecondRoute: SecondRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
